module.exports = [
    {"emoji": "🦍", "name": "Gorilla"},
    {"emoji": "🐺", "name": "Wolf"},
    {"emoji": "🐈", "name": "Cat"},
    {"emoji": "🐈‍⬛", "name": "Black Cat"},
    {"emoji": "🐯", "name": "Tiger Face"},
    {"emoji": "🐅", "name": "Tiger"},
    {"emoji": "🦁", "name": "Lion"},
    {"emoji": "🐘", "name": "Elephant"},
    {"emoji": "🦒", "name": "Giraffe"},
    {"emoji": "🐔", "name": "Chicken"},
    {"emoji": "🐷", "name": "Pig Face"},
    {"emoji": "🦜", "name": "Parrot"},
    
    
    // {"emoji": "🐒", "name": "Monkey"},
    // {"emoji": "🦧", "name": "Orangutan"},
    // {"emoji": "🐶", "name": "Dog Face"},
    // {"emoji": "🐕", "name": "Dog"},
    // {"emoji": "🦮", "name": "Guide Dog"},
    // {"emoji": "🐕‍🦺", "name": "Service Dog"},
    // {"emoji": "🐩", "name": "Poodle"},
    // {"emoji": "🦊", "name": "Fox"},
    // {"emoji": "🦝", "name": "Raccoon"},
    // {"emoji": "🐱", "name": "Cat Face"},
    // {"emoji": "🐆", "name": "Leopard"},
    // {"emoji": "🐴", "name": "Horse Face"},
    // {"emoji": "🐎", "name": "Horse"},
    // {"emoji": "🦄", "name": "Unicorn"},
    // {"emoji": "🦓", "name": "Zebra"},
    // {"emoji": "🦌", "name": "Deer"},
    // {"emoji": "🦬", "name": "Bison"},
    // {"emoji": "🐮", "name": "Cow Face"},
    // {"emoji": "🐂", "name": "Ox"},
    // {"emoji": "🐃", "name": "Water Buffalo"},
    // {"emoji": "🐄", "name": "Cow"},
    // {"emoji": "🐖", "name": "Pig"},
    // {"emoji": "🐗", "name": "Boar"},
    // {"emoji": "🐏", "name": "Ram"},
    // {"emoji": "🐑", "name": "Ewe"},
    // {"emoji": "🐐", "name": "Goat"},
    // {"emoji": "🐪", "name": "Camel"},
    // {"emoji": "🐫", "name": "Two-Hump Camel"},
    // {"emoji": "🦙", "name": "Llama"},
    // {"emoji": "🦣", "name": "Mammoth"},
    // {"emoji": "🦏", "name": "Rhinoceros"},
    // {"emoji": "🦛", "name": "Hippopotamus"},
    // {"emoji": "🐭", "name": "Mouse Face"},
    // {"emoji": "🐁", "name": "Mouse"},
    // {"emoji": "🐀", "name": "Rat"},
    // {"emoji": "🐹", "name": "Hamster"},
    // {"emoji": "🐰", "name": "Rabbit Face"},
    // {"emoji": "🐇", "name": "Rabbit"},
    // {"emoji": "🐿️", "name": "Chipmunk"},
    // {"emoji": "🦫", "name": "Beaver"},
    // {"emoji": "🦔", "name": "Hedgehog"},
    // {"emoji": "🦇", "name": "Bat"},
    // {"emoji": "🐻", "name": "Bear"},
    // {"emoji": "🐻‍❄️", "name": "Polar Bear"},
    // {"emoji": "🐨", "name": "Koala"},
    // {"emoji": "🐼", "name": "Panda"},
    // {"emoji": "🦥", "name": "Sloth"},
    // {"emoji": "🦦", "name": "Otter"},
    // {"emoji": "🦨", "name": "Skunk"},
    // {"emoji": "🦘", "name": "Kangaroo"},
    // {"emoji": "🦡", "name": "Badger"},
    // {"emoji": "🦃", "name": "Turkey"},
    // {"emoji": "🐓", "name": "Rooster"},
    // {"emoji": "🐤", "name": "Baby Chick"},
    // {"emoji": "🐦", "name": "Bird"},
    // {"emoji": "🐧", "name": "Penguin"},
    // {"emoji": "🕊️", "name": "Dove"},
    // {"emoji": "🦅", "name": "Eagle"},
    // {"emoji": "🦆", "name": "Duck"},
    // {"emoji": "🦢", "name": "Swan"},
    // {"emoji": "🦉", "name": "Owl"},
    // {"emoji": "🦤", "name": "Dodo"},
    // {"emoji": "🦩", "name": "Flamingo"},
    // {"emoji": "🦚", "name": "Peacock"},
    // {"emoji": "🐸", "name": "Frog"},
    // {"emoji": "🐊", "name": "Crocodile"},
    // {"emoji": "🐢", "name": "Turtle"},
    // {"emoji": "🦎", "name": "Lizard"},
    // {"emoji": "🐍", "name": "Snake"},
    // {"emoji": "🐉", "name": "Dragon"},
    // {"emoji": "🦕", "name": "Sauropod"},
    // {"emoji": "🦖", "name": "T-Rex"},
    // {"emoji": "🐳", "name": "Spouting Whale"},
    // {"emoji": "🐋", "name": "Whale"},
    // {"emoji": "🐬", "name": "Dolphin"},
    // {"emoji": "🦭", "name": "Seal"},
    // {"emoji": "🐟", "name": "Fish"},
    // {"emoji": "🐠", "name": "Tropical Fish"},
    // {"emoji": "🐡", "name": "Blowfish"},
    // {"emoji": "🦈", "name": "Shark"},
    // {"emoji": "🐙", "name": "Octopus"},
    // {"emoji": "🐌", "name": "Snail"},
    // {"emoji": "🦋", "name": "Butterfly"},
    // {"emoji": "🐛", "name": "Bug"},
    // {"emoji": "🐜", "name": "Ant"},
    // {"emoji": "🐝", "name": "Honeybee"},
    // {"emoji": "🪲", "name": "Beetle"},
    // {"emoji": "🐞", "name": "Lady Beetle"},
    // {"emoji": "🦗", "name": "Cricket"},
    // {"emoji": "🪳", "name": "Cockroach"},
    // {"emoji": "🕷️", "name": "Spider"},
    // {"emoji": "🦂", "name": "Scorpion"},
    // {"emoji": "🦟", "name": "Mosquito"},
    // {"emoji": "🪰", "name": "Fly"},
    // {"emoji": "🦀", "name": "Crab"},
    // {"emoji": "🦞", "name": "Lobster"},
    // {"emoji": "🦐", "name": "Shrimp"},
    // {"emoji": "🦑", "name": "Squid"},
    ];
